"""initial_migration.

Revision ID: 3859b22b6d3e
Revises:
Create Date: 2026-03-23 14:00:07.264532

"""

# Standart library imports
from typing import Sequence, Union

# Thirdparty imports
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3859b22b6d3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'apps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('external_id'),
    )
    op.create_table(
        'app_insights',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('app_id', sa.Integer(), nullable=False),
        sa.Column('avg_rating', sa.Float(), nullable=True),
        sa.Column('rating_distribution', sa.JSON(), nullable=True),
        sa.Column('top_negative_keywords', sa.JSON(), nullable=True),
        sa.Column('developer_insights', sa.Text(), nullable=True),
        sa.Column('actionable_recommendations', sa.Text(), nullable=True),
        sa.Column('last_processed_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['app_id'],
            ['apps.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'reviews',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('app_id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.String(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('author', sa.String(), nullable=True),
        sa.Column('version', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['app_id'],
            ['apps.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('external_id'),
    )
    op.create_table(
        'processed_reviews',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('review_id', sa.Integer(), nullable=False),
        sa.Column('sentiment_label', sa.String(), nullable=True),
        sa.Column('sentiment_score', sa.Float(), nullable=True),
        sa.Column('processed_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['review_id'],
            ['reviews.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('review_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_reviews')
    op.drop_table('reviews')
    op.drop_table('app_insights')
    op.drop_table('apps')
    # ### end Alembic commands ###
